fix(download-center): setup python with supported version
camunda/infra-global-github-actions pull request #279
Opened 2024-10-17 06:22 UTC by barmac

This is required due to gsutil not supporting Python 3.12 and newer. Cf. https://github.com/camunda/camunda-modeler/actions/runs/11371346205/job/31633203620#step:9:95

2024-10-17 06:37 UTC, barmac commented
Fix verified via https://github.com/camunda/camunda-modeler/actions/runs/11379519741/job/31657108665

2024-10-17 06:48 UTC, Langleu commented
@barmac, neither Chaima nor I are in the team anymore.

2024-10-17 06:56 UTC, barmac commented
Sorry, I just noticed you in the suggestions and assumed GH is right.

2024-10-17 07:32 UTC, kellervater approved these changes
LGTM :shipit:

2024-10-17 09:08 UTC, maxdanilov requested changes
I have concerns about not leaving any comment in the code on why 3.11 is the version to be pinned. This will create a maintenance confusion in the future.

2024-10-17 09:53 UTC, barmac commented
> I have concerns about not leaving any comment in the code on why 3.11 is the version to be pinned. This will create a maintenance confusion in the future.

I'll add it then.

2024-10-17 09:59 UTC, barmac commented
Comment added via https://github.com/camunda/infra-global-github-actions/pull/279/commits/1b3b940567a8196fbdd482abe83c6daaf6bbf040

BTW Google recommends to use another tool for storage: 
> Important: gsutil is not the recommended CLI for Cloud Storage. [Use gcloud storage](https://cloud.google.com/storage/docs/discover-object-storage-gcloud) commands in the Google Cloud CLI instead.

(source: https://cloud.google.com/storage/docs/gsutil)

2024-10-17 14:17 UTC, kellervater commented
@barmac 
I'll give `gcloud` storage a shot here and see if it's working with the current python version.

We assume that the `ubuntu-latest` runners, which just switched to `24.04` also have a different python version now. This may have caused the incompatibility.

2024-10-17 15:15 UTC, kellervater commented
@barmac created another PR which is using `gcloud storage` instead: 
https://github.com/camunda/infra-global-github-actions/pull/281

2024-10-18 07:14 UTC, barmac commented
Then I am closing this one. Thanks!

2024-10-18 07:14 UTC, closed without merging