feat(ci): add new action, submit-test-status
camunda/infra-global-github-actions pull request #326
Opened 2024-12-30 13:18 UTC by kalmarz

The action allows uploading test statuses from GH workflows into CI Analytics.

Related:
- camunda/team-infrastructure#608

2025-01-06 13:04 UTC, cmur2 commented on submit-test-status/README.md
> +| test_event_record    | Multi-line string that contains the details of the test events in JSONL format. One test event per line. |
I'd appreciate a link on "JSONL format" to e.g. https://jsonlines.org/ so people can look up easily what it stands for.

2025-01-06 13:06 UTC, cmur2 commented on submit-test-status/README.md
> +The scope of the `submit-test-status` action is to persist a *user-provided* test status information (whether a GHA workflow job run is considered successful or failed) into the central [CI Analytics
> (whether a GHA workflow job run is considered successful or failed)

Probably copy&pasted from submit-build-status, needs slightly different wording

2025-01-06 23:03 UTC, clementnero requested changes
I don't think bulk insert is necessary here since only one event is processed when the composite action is called.
I left some comments in the code, but In general, the same approach as in `submit-build-status` can be reused:
- one dedicated step to validate inputs
- simple insert

2025-01-06 23:17 UTC, clementnero commented on submit-test-status/action.yml
> +  test_event_record:
Sorry, I totally missed the bulk-insert requirement.
> There should be a way to bulk-insert data from a GitHub Actions run (format yet to be specified) into BigQuery to avoid many small requests.

2025-01-06 23:34 UTC, clementnero commented on submit-test-status/action.yml
> +      $BQ_COMMAND load \
As stated by the helper, _Inserts the records formatted as newline delimited JSON from file into the specified table_, `insert` command can insert multiple records at once. It is pretty fast (tested by Luca) if there is not a **huge** amount of data (I think it is the case, but to be confirmed by @cmur2 ), and gives an immediate feedback, _If there were any insert errors it prints the errors to stdout_, no need to handle/debug job results.

2025-01-07 07:42 UTC, kalmarz commented on submit-test-status/action.yml
> +      $BQ_COMMAND load \
> I am wondering if a simple insert (multiple rows) as implemented [submit-build-status](https://github.com/camunda/infra-global-github-actions/blob/main/submit-build-status/action.yml#L94-L113) would be enough ? I think bulk insert is not necessary here since there is not a huge amount of data to be processed.

My starting point was this business requirement: "There should be a way to bulk-insert data from a GitHub Actions run (format yet to be specified) into BigQuery to avoid many small requests."

Yes, we could have reused the simple insert and it would have been mad my life a MUCH easier.

2025-01-07 08:04 UTC, clementnero commented on submit-test-status/action.yml
> +      $BQ_COMMAND load \
> There should be a way to bulk-insert data from a GitHub Actions run (format yet to be specified) into BigQuery to avoid many small requests

I think Christian wanted to avoid having to call the composite action for each event, and instead have the capability to ingest a list in a single call. I don't think it's about handling huge amounts of data, in which case async job is certainly useful (so as not to block a runner for a long time, retry, etc.) That's my understanding, but I could be wrong.

2025-01-07 08:05 UTC, clementnero commented on submit-test-status/action.yml
> +      INVALID_LINES=$(jq -c 'select((has("test_name") and has("test_status")) | not)' "$TEMP_DIR/input_test_event_record.json")
Do we need to validate the other fields ?

2025-01-07 08:07 UTC, kalmarz commented on submit-test-status/action.yml
> +      $BQ_COMMAND load \
Let's hear him out then.

2025-01-07 08:39 UTC, cmur2 commented on submit-test-status/action.yml
> +      $BQ_COMMAND load \
> I think Christian wanted to avoid having to call the composite action for each event, and instead have the capability to ingest a list in a single call.

That is my main goal, yes. Imagine to most likely use case for this action: e.g. any GHA workflow in the C8 monorepo that runs thousands of unit tests. This workflow runs the unit tests and then wants to wrap up execution by submitting their results. It does that by probably calling another helper (to be built) to convert from JUnit XML or similar to our custom JSONL. Once it has the JSONL it wants to transfer them to Big Query. My requirement was about avoiding calling this action for every of the thousand of test cases, instead hand over a list of results and let this action do what is necessary.

2025-01-07 08:41 UTC, cmur2 commented on submit-test-status/action.yml
> +      $BQ_COMMAND load \
> There should be a way to bulk-insert data from a GitHub Actions run (format yet to be specified) into BigQuery to avoid many small requests.

I used "bulk" here not to refer to the Big Query feature but just in general meaning to avoid many repeated calls of the new custom GitHub Action avoiding the overhead in calling it. I assume the amount of detailed test statistics be still small data-wise.

2025-01-07 10:59 UTC, kalmarz commented on submit-test-status/README.md
> +The scope of the `submit-test-status` action is to persist a *user-provided* test status information (whether a GHA workflow job run is considered successful or failed) into the central [CI Analytics
How about simply this one?

The scope of the `submit-test-status` action is to load the *user-provided* test status information into the central [CI Analytics](https://confluence.camunda.com/display/HAN/CI+Analytics) database for later analysis.

2025-01-07 11:04 UTC, cmur2 commented on submit-test-status/README.md
> +The scope of the `submit-test-status` action is to persist a *user-provided* test status information (whether a GHA workflow job run is considered successful or failed) into the central [CI Analytics
Sounds good!

I think the next paragraph in the Markdown also was a bit specific to submit-build-status

2025-01-07 11:36 UTC, kalmarz commented on submit-test-status/action.yml
> +      INVALID_LINES=$(jq -c 'select((has("test_name") and has("test_status")) | not)' "$TEMP_DIR/input_test_event_record.json")
> Do we need to validate the other fields ?

Idk whether it's an over-engineering. We check for all the mandatory fields and every requirement is clearly documented. The BQ upload will fail anyway because it checks the input against the schema. Unfortunately it doesn't have dry run flag that we could use for an easy validation.

2025-01-07 11:49 UTC, clementnero commented on submit-test-status/action.yml
> +      INVALID_LINES=$(jq -c 'select((has("test_name") and has("test_status")) | not)' "$TEMP_DIR/input_test_event_record.json")
> The BQ upload will fail anyway because it checks the input against the schema

My primary concern is for the user to quickly see that the json input is "malformed", and which elements (if easy to implement).

> Idk whether it's an over-engineering.

Since you have a step do download the schema, I am wondering if you could use an existing composite action to validate json input, e.g. https://github.com/marketplace/actions/json-schema-validate

2025-01-07 15:49 UTC, kalmarz commented on submit-test-status/action.yml
> +      INVALID_LINES=$(jq -c 'select((has("test_name") and has("test_status")) | not)' "$TEMP_DIR/input_test_event_record.json")
As we concluded in our separate discussion: I tried the schema validation but it brought up so many additional problems that the time would require to tackle them is not worth investing. If the test input is invalid then the `bq load` command will fail in the workflow, indicating what the problem is.
Example run for a (forced) failure: https://github.com/camunda/infra-github-demo/actions/runs/12654485448/job/35262480350#step:3:276

2025-01-08 14:32 UTC, clementnero commented on submit-test-status/action.yml
> +      $BQ_COMMAND load \
I think batch load should work smoothly even if a bit 'oversize" for the use case. As discussed, a small note in the README.md would be appreciated.

2025-01-08 14:37 UTC, clementnero approved these changes
LGTM!
Only one [comment](https://github.com/camunda/infra-global-github-actions/pull/326/files#r1907277525) but not blocking.
Thank you!

2025-01-09 08:31 UTC, merged